; macros.asm

;  Copyright 2019-2026 Robin Verhagen-Guest
;
; Licensed under the Apache License, Version 2.0 (the "License");
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
;
;     http://www.apache.org/licenses/LICENSE-2.0
;
; Unless required by applicable law or agreed to in writing, software
; distributed under the License is distributed on an "AS IS" BASIS,
; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
; See the License for the specific language governing permissions and
; limitations under the License.

                        include "version.asm"           ; Auto-generated by make build

                        macro CPHL Reg16?               ; Convenience wrapper to compare HL with BC or DE
                          or a                          ; Note that sj macros can accept register literals,
                          sbc hl, Reg16?                ; so the call would be CPHL de without enclosing quotes.
                          add hl, Reg16?
                        endm

                        macro PRINTMSG Address?
                          ld hl, Address?
                          call PrintRst16
                        endm

                        macro PRINTBUFFER StartAddr?, LengthAddr?
                          ld hl, (StartAddr?)
                          ld bc, (LengthAddr?)
                          call PrintBufferProc
                        endm

                        macro ERRORIFCARRY ErrAddr?     ; Parameterised wrapper for throwing custom esxDOS-style error
                          jp nc, .continue
                          ld hl, ErrAddr?
                          jp CheckESPTimeout.HandleError
.continue:
                        endm

                        macro ERRORIFNONZERO ErrAddr?
                          jp z, .continue
                          ld hl, ErrAddr?
                          jp CheckESPTimeout.HandleError
.continue:
                        endm

                        macro WRITESTRING StringAddr?, StringLen?
                          ld hl, StringAddr?
                          ld bc, StringLen?
                          ldir
                        endm

                        macro WRITEBUFFER CommandAddrAddr?, CommandLenAddr?
                          ld hl, (CommandAddrAddr?)
                          ld bc, (CommandLenAddr?)
                          ldir
                        endm

                        macro NEXTREGREAD Register?
                          ld bc, Port.NextReg             ; Port.NextReg = $243B
                          ld a, Register?
                          call NextRegReadProc
                        endm

                        macro DECODEDECIMAL Buffer?, DigitCount?
                          ld hl, Buffer?
                          dec hl
                          ld (DecodeDecimalProc.DecimalBuffer), hl
                          ld b, DigitCount?
                          call DecodeDecimalProc
                        endm

                        macro RST8 Command?
                          rst $08
                          db Command?
                        endm        

                        macro ESPSEND Text?             ; 1 <= length(Text) <= 253
                          ld hl, .address               ; Start of the text to send
                          ld e, .continue-.address      ; Length of the text to send, including terminating CRLF
                          jp ESPSendProc                ; Remaining send code is generic and reusable
.address:                 db Text?                      ; Text bytes get planted at the end of the macro
                          db CR, LF                     ; Followed by CRLF
.continue:
                        endm                            ; ESPSendProc jumps back to the address after the CRLF.

                        macro ESPSENDBYTES Address?, Length? ; 1 <= length(Text) <= 255 - MUST HAVE CRLF termination
                          ld hl, Address?               ; Start of the text to send
                          ld e, Length?                 ; Length of the text to send, including terminating CRLF
                          jp ESPSendProc                ; Remaining send code is generic and reusable
                        endm                            ; ESPSendProc jumps back to the address after the CRLF.

                        macro ESPSENDBUFFER Address?    ; 1 <= length(Text) <= 255 - MUST HAVE CRLF termination
                          ld hl, Address?               ; Start of the text to send
                          call GetBufferLength          ; returns with length in e and hl preserved
                          call ESPSendBufferProc        ; Remaining send code is generic and reusable
                        endm

                        macro ESPSENDBUFFERLEN Address?, LenAddr? ; 1 <= length(Text) <= 255 - MUST HAVE CRLF termination
                          ld hl, Address?               ; Start of the text to send
                          ld de, (LenAddr?)
                          call ESPSendBufferProc        ; Remaining send code is generic and reusable
                        endm