; version.asm
;
; Auto-generated by ZXVersion.exe
; On 31 Jan 2020 at 13:27

BuildNo                 macro()
                        db "63"
mend

BuildNoValue            equ "63"
BuildNoWidth            equ 0 + FW6 + FW3



BuildDate               macro()
                        db "31 Jan 2020"
mend

BuildDateValue          equ "31 Jan 2020"
BuildDateWidth          equ 0 + FW3 + FW1 + FWSpace + FWJ + FWa + FWn + FWSpace + FW2 + FW0 + FW2 + FW0



BuildTime               macro()
                        db "13:27"
mend

BuildTimeValue          equ "13:27"
BuildTimeWidth          equ 0 + FW1 + FW3 + FWColon + FW2 + FW7



BuildTimeSecs           macro()
                        db "13:27:45"
mend

BuildTimeSecsValue      equ "13:27:45"
BuildTimeSecsWidth      equ 0 + FW1 + FW3 + FWColon + FW2 + FW7 + FWColon + FW4 + FW5
