; version.asm
;
; Auto-generated by ZXVersion.exe
; On 23 Dec 2019 at 20:25

BuildNo                 macro()
                        db "34"
mend

BuildNoValue            equ "34"
BuildNoWidth            equ 0 + FW3 + FW4



BuildDate               macro()
                        db "23 Dec 2019"
mend

BuildDateValue          equ "23 Dec 2019"
BuildDateWidth          equ 0 + FW2 + FW3 + FWSpace + FWD + FWe + FWc + FWSpace + FW2 + FW0 + FW1 + FW9



BuildTime               macro()
                        db "20:25"
mend

BuildTimeValue          equ "20:25"
BuildTimeWidth          equ 0 + FW2 + FW0 + FWColon + FW2 + FW5



BuildTimeSecs           macro()
                        db "20:25:47"
mend

BuildTimeSecsValue      equ "20:25:47"
BuildTimeSecsWidth      equ 0 + FW2 + FW0 + FWColon + FW2 + FW5 + FWColon + FW4 + FW7
