; version.asm
;
; Auto-generated by ZXVersion.exe
; On 06 Feb 2020 at 12:25

BuildNo                 macro()
                        db "64"
mend

BuildNoValue            equ "64"
BuildNoWidth            equ 0 + FW6 + FW4



BuildDate               macro()
                        db "06 Feb 2020"
mend

BuildDateValue          equ "06 Feb 2020"
BuildDateWidth          equ 0 + FW0 + FW6 + FWSpace + FWF + FWe + FWb + FWSpace + FW2 + FW0 + FW2 + FW0



BuildTime               macro()
                        db "12:25"
mend

BuildTimeValue          equ "12:25"
BuildTimeWidth          equ 0 + FW1 + FW2 + FWColon + FW2 + FW5



BuildTimeSecs           macro()
                        db "12:25:14"
mend

BuildTimeSecsValue      equ "12:25:14"
BuildTimeSecsWidth      equ 0 + FW1 + FW2 + FWColon + FW2 + FW5 + FWColon + FW1 + FW4
